name: cppt_tools
version: 1.0.0
publish_to: none
description: cppt tools for hospital
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  encrypt: ^5.0.1
  hive: ^3.0.0-dev
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  # flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  go_router: ^7.1.1
  get: ^4.6.5
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

