name: cppt_tools
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-129.0.dev <4.0.0'

dependencies: 
  get: 4.6.5
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  # firebase_core: 2.13.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

